---
title: "Probability in R"
author: "Ben Weinstein"
date: "Wednesday, March 11, 2015"
output:
  html_document:
    keep_md: yes
---

#Formative

###Which probability distribution should we use to model coin flips given a finite number of trials?

* Binomial 
* Negative Binomial 
* Normal 
* Poisson 

#Summative
###What is the probability of getting three heads in ten coin flips?

```{r,echo=FALSE,warning=FALSE,message=F,fig.width=8,fig.height=5}
library(ggplot2)
library(knitr)
opts_chunk$set(fig.path='figure/',fig.align='center')

x<-seq(0,10,1)
y<-dbinom(10,x,0.5)
A<-ggplot(data.frame(x=x,y=y),aes(x=as.factor(x),y=y)) + geom_point(aes(group=1)) + theme_bw() + geom_point(x=4,y=dbinom(x=10,size=3,prob=0.5),col='red',size=10) + labs(y="Probability",x="# of heads") + geom_line(aes(group=1)) + ggtitle("A: dbinom(x=10,size=3,prob=0.5)")

x<-seq(0,10,1)
y<-dbinom(x,7,0.5)
B<-ggplot(data.frame(x=x,y=y),aes(x=as.factor(x),y=y)) + geom_point(aes(group=1)) + theme_bw() + geom_point(x=4,y=dbinom(x=3,size=7,prob=0.5),col='red',size=10) + labs(y="Probability",x="# of heads") + geom_line(aes(group=1)) + ggtitle("B: dbinom(x=3,size=7,prob=0.5)")

x<-seq(0,10,1)
y<-dbinom(x,10,0.5)
C<-ggplot(data.frame(x=x,y=y),aes(x=as.factor(x),y=y)) + geom_point(aes(group=1)) + theme_bw() + geom_point(x=4,y=dbinom(3,10,0.5),col='red',size=10) + labs(y="Probability",x="# of heads") + geom_line(aes(group=1)) + ggtitle("C: dbinom(x=3,size=10,prob=0.5)")

x<-seq(0,10,1)
y<-pbinom(x,10,0.5)
D<-ggplot(data.frame(x=x,y=y),aes(x=as.factor(x),y=y)) + geom_point(aes(group=1)) + theme_bw() + geom_point(x=4,y=pbinom(3,10,0.5),col='red',size=10) + labs(y="Probability",x="# of heads") + geom_line(aes(group=1)) + ggtitle("D: pbinom(x=3,size=10,prob=0.5)")


library(gridExtra)
grid.arrange(A,B,C,D)
```

#Explanation and distractors

A. The size of the draw and number of successes are reversed. Good conceptual test - since it is nonsensical to draw 10 heads from 3 flips.

B. The total number of flips is 10 not 7, students selecting this option see the binomial trial as successes and failures, so 10-3=7. It has a reasonable shape, but the probability is too high.

C. Correct answer, the probability of getting three heads in 10 draws is around 0.11

D. The student has confused with the probability of a point estimate (3 heads) denoted by the dbinom density function with the probability of getting 3 or less heads, which is the cumulative distribution function pbinom. While the estimate is not that far off, the increasing function towards ten should seem wrong.


